export const API_RESPONSE_SUCCESS = "API_RESPONSE_SUCCESS";
export const API_RESPONSE_ERROR = "API_RESPONSE_ERROR";

export const GET_LAYOUT = "GET_LAYOUT";

export const UPDATE_INTERNAL_LAYOUT = "UPDATE_INTERNAL_LAYOUT";
export const UPDATE_LAYOUT_SUCCESS = "UPDATE_LAYOUT_SUCCESS";
export const UPDATE_LAYOUT_ERROR = "UPDATE_LAYOUT_ERROR";
